"""Erpy's icon, and the add-on icons built from it.

    python3 icon-gen.py            # writes every icon into its repo
    python3 icon-gen.py <outdir>   # writes them all under <outdir> instead, for previewing

The vendor marks are in icon-marks/marks.json (path data lifted from each vendor's
published logo, or Simple Icons) with bounding boxes measured in Chrome in
icon-marks/bbox.json.

Erpy follows the family icon standard: 100x100 viewBox, a flat accent tile with
rx=22.44, and a #FEFEFE glyph made only of filled geometry, so icon-mask.svg can
be the same glyph with nothing removed.

The glyph is a hub wired to eight nodes: the one engine every system plugs into.
Each add-on icon is that icon with a triangle in the bottom-left corner, in the
ERP's colour, carrying the ERP's mark. The bottom-left spoke runs into the
triangle, so the connector reads as plugged in.
"""
import json, math, os, sys

TILE = '#2A6B4C'
GLYPH = '#FEFEFE'
R_TILE = 22.44
LEG = 50          # triangle legs: corner (0,100), (0,100-LEG), (LEG,100)
GAP = 2.6         # tile-coloured band between triangle and glyph
MARGIN = 2.8      # breathing room around a mark inside the triangle

def f(v):
    s = f'{v:.2f}'.rstrip('0').rstrip('.')
    return '0' if s in ('', '-0') else s

# ---------------------------------------------------------------- the glyph
def rrect(x, y, w, h, r):
    return (f'M{f(x+r)} {f(y)}H{f(x+w-r)}A{f(r)} {f(r)} 0 0 1 {f(x+w)} {f(y+r)}'
            f'V{f(y+h-r)}A{f(r)} {f(r)} 0 0 1 {f(x+w-r)} {f(y+h)}'
            f'H{f(x+r)}A{f(r)} {f(r)} 0 0 1 {f(x)} {f(y+h-r)}'
            f'V{f(y+r)}A{f(r)} {f(r)} 0 0 1 {f(x+r)} {f(y)}Z')

def circle(cx, cy, r):
    return (f'M{f(cx-r)} {f(cy)}A{f(r)} {f(r)} 0 1 0 {f(cx+r)} {f(cy)}'
            f'A{f(r)} {f(r)} 0 1 0 {f(cx-r)} {f(cy)}Z')

def poly(*pts):
    return 'M' + 'L'.join(f'{f(x)} {f(y)}' for x, y in pts) + 'Z'

def bar(x1, y1, x2, y2, w):
    """A filled bar of width w from (x1,y1) to (x2,y2)."""
    dx, dy = x2 - x1, y2 - y1
    L = math.hypot(dx, dy)
    nx, ny = -dy / L * w / 2, dx / L * w / 2
    return poly((x1+nx, y1+ny), (x2+nx, y2+ny), (x2-nx, y2-ny), (x1-nx, y1-ny))

def glyph():
    """Returns a list of (d, evenodd) pieces."""
    parts = []
    # The hub: a rounded square ring, with the exchange arrows inside it.
    parts.append((rrect(33, 33, 34, 34, 7) + rrect(39.5, 39.5, 21, 21, 3), True))
    parts.append((poly((42, 43.6), (51.6, 43.6), (51.6, 40.6), (57.6, 45.1),
                       (51.6, 49.6), (51.6, 46.6), (42, 46.6)), False))
    parts.append((poly((58, 56.4), (48.4, 56.4), (48.4, 59.4), (42.4, 54.9),
                       (48.4, 50.4), (48.4, 53.4), (58, 53.4)), False))
    # Four straight spokes to ring nodes — the systems Erpy talks to.
    for (x1, y1, x2, y2, cx, cy) in [(50, 33, 50, 21, 50, 15), (67, 50, 79, 50, 85, 50),
                                     (50, 67, 50, 79, 50, 85), (33, 50, 21, 50, 15, 50)]:
        parts.append((bar(x1, y1, x2, y2, 5), False))
        parts.append((circle(cx, cy, 7) + circle(cx, cy, 3), True))
    # Four diagonal spokes to solid nodes, from the hub's rounded corners.
    k = 33 + 7 - 7 / math.sqrt(2)          # where the corner arc meets 45 degrees
    for sx, sy in [(-1, -1), (1, -1), (1, 1), (-1, 1)]:
        hx, hy = 50 + sx * (50 - k), 50 + sy * (50 - k)
        nx, ny = 50 + sx * 28.5, 50 + sy * 28.5
        parts.append((bar(hx, hy, nx, ny, 4.4), False))
        parts.append((circle(nx, ny, 5.2), False))
    return parts

def glyph_svg(fill):
    out = []
    for d, eo in glyph():
        rule = ' fill-rule="evenodd"' if eo else ''
        out.append(f'        <path{rule} d="{d}"/>')
    return f'    <g fill="{fill}">\n' + '\n'.join(out) + '\n    </g>'

def erpy_icon():
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
    <!-- Erpy: one hub wired to eight systems, with the exchange arrows inside it.
         The family standard: flat tile, rx 22.44, filled #FEFEFE glyph (no strokes),
         so icon-mask.svg is this glyph unchanged. Generated by craft-erpy/promos/icon-gen.py. -->
    <rect x="0" y="0" width="100" height="100" rx="{R_TILE}" fill="{TILE}"/>
{glyph_svg(GLYPH)}
</svg>
'''

def erpy_mask():
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
    <!-- icon.svg's glyph with the tile removed. Craft colours it for the CP nav.
         Generated by craft-erpy/promos/icon-gen.py; keep the two in step by regenerating. -->
{glyph_svg('currentColor')}
</svg>
'''

def erpy_watermark():
    # The glyph blown up and cropped: no tile, so no hard-edged box on the slide,
    # and the spokes run off the edge so nothing closes back into a rectangle.
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="12 12 76 76">
{glyph_svg('#FFFFFF')}
</svg>
'''

# ---------------------------------------------------------------- add-ons
def inside(x, y):
    """Is (x,y) at least MARGIN inside both the triangle and the tile's rounded corner?"""
    if (y - x - (100 - LEG)) / math.sqrt(2) < MARGIN:       # hypotenuse
        return False
    if y > 100 - MARGIN - 1.2 or x < MARGIN:               # tile edges
        return False
    cx, cy = R_TILE, 100 - R_TILE
    if x < cx and y > cy and math.hypot(x - cx, y - cy) > R_TILE - MARGIN:
        return False
    return True

def fit(w, h, cap):
    """Largest box of aspect w:h (height capped) that fits; returns x, y, scale."""
    best = None
    for i in range(1, 400):
        s = i * 0.002 * 100 / max(w, h)
        bw, bh = w * s, h * s
        if bh > cap:
            break
        ok = None
        for yb in [100 - MARGIN - 1.2 - j * 0.25 for j in range(120)]:
            y0 = yb - bh
            for xa in [MARGIN + j * 0.25 for j in range(120)]:
                if all(inside(px, py) for px, py in
                       [(xa, y0), (xa + bw, y0), (xa, yb), (xa + bw, yb), (xa, (y0+yb)/2)]):
                    ok = (xa, y0)
                    break
            if ok:
                break
        if not ok:
            break
        best = (ok[0], ok[1], s)
    return best

ADDONS = {
    # repo suffix: (display name, triangle colour, mark colour or None to keep the mark's own, colour map, height cap)
    'acumatica':       ('Acumatica',        '#0092CC', '#FFFFFF', None, 19),
    'afas':            ('AFAS',             '#1B5FB4', '#FFFFFF', None, 19),
    'businesscentral': ('Business Central', '#0B53CE', '#FFFFFF', None, 19),
    'exactonline':     ('Exact Online',     '#E1141D', '#FFFFFF', None, 19),
    'myob':            ('MYOB',             '#6100A5', '#FFFFFF', None, 19),
    'netsuite':        ('NetSuite',         '#125580', None, {'#125580': '#FFFFFF', '#baccdb': '#8FB6D6'}, 19),
    'odoo':            ('Odoo',             '#714B67', '#FFFFFF', None, 19),
    'priority':        ('Priority',         '#16213D', None, None, 19),
    'sage':            ('Sage',             '#101312', '#00D639', None, 19),
    'sapb1':           ('SAP Business One', '#0070F2', '#FFFFFF', None, 19),
    'unit4':           ('Unit4',            '#FFFFFF', '#000000', None, 19),
    'visma':           ('Visma',            '#7F56FA', '#FFFFFF', None, 19),
}

def addon_icon(vendor, marks, bboxes):
    name, bg, fg, cmap, cap = ADDONS[vendor]
    bx, by, bw, bh = bboxes[vendor]
    x, y, s = fit(bw, bh, cap)
    # centre the mark in whatever room is left, a touch smaller than the maximum
    s2 = s * 0.96
    x += (bw * s - bw * s2) / 2
    y += (bh * s - bh * s2) / 2
    tx, ty = x - bx * s2, y - by * s2
    paths = []
    for d, fill in marks[vendor]:
        colour = fg or (cmap or {}).get(fill, fill)
        paths.append(f'            <path fill="{colour}" d="{d}"/>')
    gap = GAP * math.sqrt(2)
    clip = f'erpy-{vendor}-tile'
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
    <!-- Erpy for {name}: Erpy's icon with the ERP's mark in the corner, where the
         bottom-left spoke plugs in. The mark belongs to its owner and is used only
         to say which ERP this add-on connects to. Generated by craft-erpy/promos/icon-gen.py. -->
    <defs>
        <clipPath id="{clip}">
            <rect x="0" y="0" width="100" height="100" rx="{R_TILE}"/>
        </clipPath>
    </defs>
    <rect x="0" y="0" width="100" height="100" rx="{R_TILE}" fill="{TILE}"/>
{glyph_svg(GLYPH)}
    <g clip-path="url(#{clip})">
        <path fill="{TILE}" d="{poly((0, 100 - LEG - gap), (LEG + gap, 100), (0, 100))}"/>
        <path fill="{bg}" d="{poly((0, 100 - LEG), (LEG, 100), (0, 100))}"/>
        <g transform="translate({f(tx)} {f(ty)}) scale({s2:.5f})">
{chr(10).join(paths)}
        </g>
    </g>
</svg>
'''

def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, 'w').write(text)
    print('  wrote', os.path.relpath(path))

if __name__ == '__main__':
    here = os.path.dirname(os.path.abspath(__file__))
    marks = json.load(open(os.path.join(here, 'icon-marks', 'marks.json')))
    bboxes = json.load(open(os.path.join(here, 'icon-marks', 'bbox.json')))
    if len(sys.argv) > 1:
        out = sys.argv[1]
        erpy = {'icon': f'{out}/erpy/icon.svg', 'mask': f'{out}/erpy/icon-mask.svg',
                'watermark': f'{out}/erpy/watermark.svg'}
        addon = lambda v: [f'{out}/{v}/icon.svg']
    else:
        repo = os.path.dirname(here)                 # craft-erpy
        sites = os.path.dirname(repo)
        erpy = {'icon': f'{repo}/src/icon.svg', 'mask': f'{repo}/src/icon-mask.svg',
                'watermark': f'{here}/assets/watermark.svg', 'promo': f'{here}/assets/icon.svg'}
        # each add-on's own icon and promo copy, plus the copy Erpy's family slide shows
        addon = lambda v: [f'{sites}/craft-erpy-{v}/src/icon.svg',
                           f'{sites}/craft-erpy-{v}/promos/assets/icon.svg',
                           f'{here}/assets/addons/{v}.svg']
    write(erpy['icon'], erpy_icon())
    if 'promo' in erpy:
        write(erpy['promo'], erpy_icon())
    write(erpy['mask'], erpy_mask())
    write(erpy['watermark'], erpy_watermark())
    for v in ADDONS:
        for path in addon(v):
            write(path, addon_icon(v, marks, bboxes))
